engines:
  eslint:
    enabled: true
  isort:
    enabled: true
    channel: beta
  pep8:
    enabled: true
  pylint:
    enabled: true
    channel: beta
    plugins:
    - celery
    - django
    checks:
      import-error:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 100
          python_version: 3
exclude_patterns:
- ".*"
- "**/__pycache__/"
- "**/migrations/"
- "node_modules/"
- "tests/"
- "**/test_*"
ratings:
  paths:
  - saleor/**
