language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
cache:
  pip: true
  directories:
    - node_modules
install:
  - pip install -U pip setuptools wheel
  - pip install tox-travis codecov
  - nvm install 8
  - npm i
  - npm run build-assets --production
  - npm run build-emails
script:
  - tox
env:
  global:
    - DJANGO_SETTINGS_MODULE=tests.settings
    - DATABASE_URL='postgres://postgres@localhost:5432/saleor'
  matrix:
  - DJANGO="1.11"
  - DJANGO="2.0"
  - DJANGO="2.1"
  - DJANGO="master"
matrix:
  include:
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="2.0"
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="2.1"
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="master"
  allow_failures:
    - python: "3.5"
      env: DJANGO="2.1"
    - python: "3.5"
      env: DJANGO="master"
    - python: "3.6"
      env: DJANGO="2.1"
    - python: "3.6"
      env: DJANGO="master"
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="2.1"
    - python: "3.7"
      env: DJANGO="master"
      sudo: required
      dist: xenial
  exclude:
    - python: "3.4"
      env: DJANGO="2.1"
    - python: "3.4"
      env: DJANGO="master"
after_success:
  - codecov
services:
  - postgresql
