language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
install:
  - python setup.py install
  - pip install coverage
  - pip install codecov
script: coverage run setup.py test
after_success:
  - codecov
