language: python
python:
- 2.7
- 3.3
- 3.4
install:
- python setup.py install
script:
- export DJANGO_SETTINGS_MODULE=saleor.test_settings
- python setup.py test
notifications:
  webhooks: https://webhooks.gitter.im/e/af18bf2decb40329066b
