language: python
sudo: false
install:
  - pip install tox codecov
script:
  - tox
env:
  - TOXENV=py27-django18
  - TOXENV=py27-django_master
  - TOXENV=py33-django18
  - TOXENV=py33-django_master
  - TOXENV=py34-django18
  - TOXENV=py34-django_master
matrix:
  allow_failures:
    - env: TOXENV=py27-django_master
    - env: TOXENV=py33-django_master
    - env: TOXENV=py34-django_master
after_success:
  - codecov
