language: python
cache:
  pip: true
  directories:
    - node_modules
sudo: false
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.5-dev
install:
  - pip install -U pip setuptools wheel
  - pip install tox codecov
  - nvm install 8
  - npm i
  - npm run build-assets --production
script:
  - tox
env:
  global:
    - DJANGO_SETTINGS_MODULE=tests.settings
    - DATABASE_URL='postgres://postgres@localhost:5432/saleor'
  matrix:
    - TOXENV=py27-django111
    - TOXENV=py34-django111
    - TOXENV=py34-django_master
    - TOXENV=py35-django111
    - TOXENV=py35-django_master
    - TOXENV=py36-django111
    - TOXENV=py36-django_master
matrix:
  allow_failures:
    - env: TOXENV=py34-django_master
    - env: TOXENV=py35-django_master
    - env: TOXENV=py36-django_master
after_success:
  - codecov
services:
  - postgresql
