version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    ports:
      - '127.0.0.1:5432:5432'
  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery worker -A saleor.celery
    volumes:
      - .:/app:Z
    links:
      - redis
    depends_on:
      - redis
  search:
    image: elasticsearch:5.4
    ports:
      - '127.0.0.1:9200:9200'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://saleor:saleor@db/saleor
      - DEFAULT_FROM_EMAIL=noreply@example.com
      - ELASTICSEARCH_URL=http://search:9200
      - OPENEXCHANGERATES_API_KEY
      - REDIS_URL=redis://redis:6379/0
      - REDIS_BROKER_URL=redis://redis:6379/1
      - SECRET_KEY=changeme
    depends_on:
      - db
      - redis
      - search
    ports:
      - '8000:8000'
    volumes:
      - .:/app:Z
