db:
  image: sameersbn/postgresql:9.4
  environment:
    - DB_NAME=saleor
    - DB_USER=saleor
    - DB_PASS=saleor
redis:
  image: redis
mailcatcher:
 image: schickling/mailcatcher
 ports:
  - '1080:1080'
web:
  build: .
  environment:
    - SECRET_KEY=changeme
    - DEFAULT_FROM_EMAIL=info@getsaleor.com
    - EMAIL_BACKEND_MODULE=smtp
    - EMAIL_HOST=mailcatcher
    - EMAIL_PORT=1025
  links:
    - db
    - mailcatcher
    - redis
  ports:
    - '8000:8000'
  volumes:
    - .:/app
