version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    ports:
      - '127.0.0.1:5432:5432'
  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: common.env
    command: /app/virtualenv/bin/celery -A saleor worker --app=saleor.celeryconf:app --loglevel=info
    volumes:
      - ./saleor:/app/saleor:Z
      - ./locale:/app/locale:Z
      - ./templates:/app/templates:Z
    links:
      - redis
    depends_on:
      - redis
  search:
    image: elasticsearch:5.4.3
    mem_limit: 512m
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '127.0.0.1:9200:9200'
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: common.env
    depends_on:
      - db
      - redis
      - search
    ports:
      - '8000:8000'
    volumes:
      - ./saleor:/app/saleor:Z
      - ./locale:/app/locale:Z
      - ./templates:/app/templates:Z
