version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Set version
          command: |
            export SALEOR_VERSION=$(git rev-parse --short HEAD)
            if [ -n "$CIRCLE_TAG" ]; then
              export SALEOR_VERSION=$(git describe --tags)
            fi
            sed -i.bak "s#'dev'#'$SALEOR_VERSION'#" saleor/__init__.py


      - run:
          name: Build application Docker image
          command: |
            docker build \
              --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
              --build-arg AWS_LOCATION=$AWS_LOCATION \
              --build-arg AWS_MEDIA_BUCKET_NAME=$AWS_MEDIA_BUCKET_NAME \
              --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
              --build-arg AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME \
              --build-arg STATIC_URL=$STATIC_URL \
              -t mirumee/saleor:latest .
      - run:
          name: Run tests
          command: |
            docker run -d --name db circleci/postgres:latest
            docker run --network container:db --rm -e DATABASE_URL -e DJANGO_SETTINGS_MODULE -e SECRET_KEY mirumee/saleor:latest pytest
          environment:
            DATABASE_URL: postgres://root:@localhost:5432/circle_test
            DJANGO_SETTINGS_MODULE: saleor.settings
            SECRET_KEY: irrelevant
      - deploy:
          name: Push Docker image
          command: |
            docker login -u $DOCKERCLOUD_USER -p $DOCKERCLOUD_PASS
            docker tag mirumee/saleor:latest mirumee/saleor:$CIRCLE_SHA1
            docker push mirumee/saleor:$CIRCLE_SHA1
            docker push mirumee/saleor:latest

      - run:
          name: Deploy saleor-demo
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              apk add --upgrade --no-cache curl libcurl
              sh ./scripts/push_static.sh
              curl -u $DEMO_DEPLOY_KEY: \
                -d build_parameters[CIRCLE_JOB]=deploy \
                https://circleci.com/api/v1.1/project/github/mirumee/saleor-demo/tree/master
            fi

      - run:
          name: Deploy saleor master
          command: |
            apk add --upgrade --no-cache zip py-pip
            pip install awscli
            sh ./scripts/deploy_master.sh > /dev/null 2>&1


workflows:
  version: 2
  build-deploy:
    jobs:
        - build:
            filters:
              branches:
                only: master
              tags:
                only: /demo.*/
