name: TEST-ENV-CLEANUP
# Build and deploy test instance for every pull request

on:
  pull_request:
    # trigger on "edited" to update instance when configuration changes in PR description
    types: [closed]
    branches: ["*"]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: rlespinasse/github-slug-action@2.0.0

      - name: Invoke deployment lambda
        uses: gagoar/invoke-aws-lambda@v3.3.0
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: us-east-1
          FunctionName: test-env-manager
          Payload: >-
            {
              "action": "${{ github.event.action }}",
              "label": "${{ env.GITHUB_HEAD_REF_SLUG_URL }}",
              "image": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/saleor-testenvs:${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
            }
          LogType: Tail

      - name: Mark deployment as deactivated
        uses: bobheadxi/deployments@v0.4.2
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.GITHUB_HEAD_REF_SLUG_URL }}
